local binds = require("binds")
local monitors = require("monitors")
local appearance = require("appearance")
local autostart = require("autostart")
local animations = require("animations")

hl.config({
    autogenerated = false,
})

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")

-- Disable anime mascot wallpaper
-- It also disables Hyprland logo.
hl.config({
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = false,
    },
})
